using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bmazon.Data
{
    public abstract class Account
    {
        //[DatabaseGenerated(DatabaseGeneratedOption.None)] //Key is generated by user not the system
        [Required]
        [Key]
        public string Email { get; set; }

        [MinLength(2)]
        [MaxLength(50)]
        public string FirstName { get; set; }

        [MinLength(2)]
        [MaxLength(50)]
        public string LastName { get; set; }

        public string PhoneNumber { get; set; }
    }

    public class Seller : Account
    {
        [Index("CompanyIndex", IsUnique = true)]
        public string Company { get; set; }

        public double Earning { get; set; }

        public virtual IEnumerable<Review> Reviews { get; set; }

        public virtual IEnumerable<Order> Orders { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }

    public class Customer : Account
    {
        public string BillingAddress { get; set; }

        public string ShippingAddress { get; set; }

        public Cart Cart { get; set; }

        public virtual ICollection<Review> Reviews { get; set; }

        public virtual ICollection<Order> Orders { get; set; }

        public virtual ICollection<PaymentOption> PaymentOptions { get; set; }

    }
}
